# Generated by Django 3.1.2 on 2020-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
