# Generated by Django 3.1.2 on 2020-11-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='phone',
        ),
    ]
